version: '3'
services:
  config:
    build:
      context: ./Edges/config-service/
    ports:
      - 8888:8888
    volumes:
      - /containers/config
    networks: 
    - web

  eureka:
    build:
      context: ./Edges/eureka-service/
    ports:
      - 8761:8761
    depends_on: 
    - config
    volumes:
      - /containers/eureka
    networks: 
    - web

  spring-admin:
    build:
      context: ./Edges/spring-admin/
    ports:
      - 8087:8087
    depends_on: 
    - config
    - eureka
    volumes:
      - /containers/spring-admin
    networks: 
    - web

  commandes:
    build:
      context: ./Commandes
    depends_on:
      - config
      - eureka
    ports:
      - 9002:9002
    volumes:
      - /containers/commandes
    networks: 
    - web

  paiement:
    build:
      context: ./Paiement
    depends_on:
      - config
      - eureka
    ports:
      - 9003:9003
    volumes:
      - /containers/paiement
    networks: 
    - web

  zuul-proxy:
    build:
      context: ./Edges/zuul-proxy
    depends_on:
      - config
      - eureka
    ports:
      - 9004:9004
    volumes:
      - /containers/zuul-proxy
    networks: 
    - web

  springcloud-gateway:
    build:
      context: ./Edges/springCloud-gateway
    depends_on:
      - config
      - eureka
    ports:
      - 8088:8088
    volumes:
      - /containers/springcloud-gateway
    networks: 
    - web

  zuul-client:
    build:
      context: ./Clients/zuul-client
    depends_on:
      - config
      - eureka
    ports:
      - 8000:8000
    volumes:
      - /containers/zuul-client
    networks: 
    - web

  springcloudgateway-client:
    build:
      context: ./Clients/springCloudGateway-client
    depends_on:
      - config
      - eureka
    ports:
      - 8001:8001
    volumes:
      - /containers/springcloudgateway-client
    networks: 
    - web

  mysql-container:
    image: mysql
    depends_on:
      - eureka
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_produits
    ports:
      - "3306:3306"
    volumes:
      - /containers/mysql/db_produits
    networks:
      - web

  produits:
    build:
      context: ./Produits
    depends_on:
      - mysql-container
      - config
      - eureka
    ports:
      - 9001:9001
    environment:
      DATABASE_HOST: mysql-container
      DATABASE_USER: root
      DATABASE_password: root
      DATABASE_NAME: db_produits
      DATABASE_PORT: 3306
    volumes:
      - /containers/produits
    networks:
      - web

  zipkin:
    build:
      context: ./Edges/zipkin/
    image: zipkin
    ports:
      - 9411:9411
    networks:
      - web
    



networks: 
  web:
    driver: bridge
