INSERT INTO COMMANDE (ID , PRODUCT_ID ,DATE_COMMANDE ,QUANTITE ,COMMANDE_PAYEE ) VALUES (0,0,TO_DATE('17/12/2015', 'DD/MM/YYYY'), 22, false );

INSERT INTO COMMANDE (ID , PRODUCT_ID ,DATE_COMMANDE ,QUANTITE ,COMMANDE_PAYEE ) VALUES (1,0,TO_DATE('17/12/2015', 'DD/MM/YYYY'), 22, false );

INSERT INTO COMMANDE (ID , PRODUCT_ID ,DATE_COMMANDE ,QUANTITE ,COMMANDE_PAYEE ) VALUES (2,2,TO_DATE('17/12/2015', 'DD/MM/YYYY'), 30, true );

INSERT INTO COMMANDE (ID , PRODUCT_ID ,DATE_COMMANDE ,QUANTITE ,COMMANDE_PAYEE ) VALUES (3,3,TO_DATE('17/12/2015', 'DD/MM/YYYY'), 55, false );

INSERT INTO COMMANDE (ID , PRODUCT_ID ,DATE_COMMANDE ,QUANTITE ,COMMANDE_PAYEE ) VALUES (4,4,TO_DATE('17/12/2015', 'DD/MM/YYYY'), 36, true );

INSERT INTO COMMANDE (ID , PRODUCT_ID ,DATE_COMMANDE ,QUANTITE ,COMMANDE_PAYEE ) VALUES (5,5,TO_DATE('17/12/2015', 'DD/MM/YYYY'), 58, false );

INSERT INTO COMMANDE (ID , PRODUCT_ID ,DATE_COMMANDE ,QUANTITE ,COMMANDE_PAYEE ) VALUES (6,6,TO_DATE('17/12/2015', 'DD/MM/YYYY'), 89, true );

INSERT INTO COMMANDE (ID , PRODUCT_ID ,DATE_COMMANDE ,QUANTITE ,COMMANDE_PAYEE ) VALUES (7,7,TO_DATE('17/12/2015', 'DD/MM/YYYY'), 78, true );

