- hosts: all
  gather_facts: True
  any_errors_fatal: true
  debugger: on_failed

  tasks:

  - name: install chaostoolkit
    pip:
      name: chaostoolkit
      virtualenv: ~/.venvs/chaostk

  - name: ensure chaostoolkit is at the latest version
    pip:
      name: chaostoolkit
      virtualenv: ~/.venvs/chaostk
      state: latest

  - name: install chaosspring Extension
    pip:
      name: chaostoolkit-spring
      virtualenv: ~/.venvs/chaostk

  - name: ensure chaosspring is at the latest version
    pip:
      name: chaostoolkit-spring
      virtualenv: ~/.venvs/chaostk
      state: latest

  - name: install chaos-reporting Extension
    pip:
      name: chaostoolkit-reporting
      virtualenv: ~/.venvs/chaostk

  - name: ensure chaos-reporting is at the latest version
    pip:
      name: chaostoolkit-reporting
      virtualenv: ~/.venvs/chaostk
      state: latest
